### ISSUE TITLE
[0083-RFPR-066]: Add tests coverage for teams allow_list

### ISSUE THREAD

**Issue by gordsport** [vegaprotocol/core-test-coverage#667] opened 2024-01-16 10:15 UTC
If a party submits a JoinTeam transaction and the team is closed then the party will not be added to the team if they are not specified in the allow_list. ([0083-RFPR-066](https://github.com/vegaprotocol/specs/blob/palazzo/protocol/0083-RFPR-on_chain_referral_program.md#0083-RFPR-066)).

**Comment by guoguojin** [comment] 2024-01-17 12:25
Closing as this is a duplicate of https://github.com/vegaprotocol/core-test-coverage/issues/526 and already resolved

**Closed by guoguojin** 2024-01-17 12:25 UTC
Labels: system-test
