### ISSUE TITLE
[0056-REWA-109]: Add extra validator ranking reward metric AC

### ISSUE THREAD

**Issue by gordsport** [vegaprotocol/core-test-coverage#972] opened 2024-02-13 17:45 UTC
- https://github.com/vegaprotocol/specs/blob/palazzo/protocol/0056-REWA-rewards_overview.md#0056-REWA-109

**Comment by Sohill-Patel** [comment] 2024-02-14 17:43
duplicate of https://github.com/vegaprotocol/core-test-coverage/issues/973

**Closed by Sohill-Patel** 2024-02-14 17:43 UTC
Labels: system-test
