### ISSUE TITLE
Add test coverage for Colosseo 0014-NP-VAMM-004

### ISSUE THREAD

**Issue by witgaw** [vegaprotocol/core-test-coverage#1328] opened 2024-05-15 08:53 UTC
Add test coverage for Palazzo [0014-NP-VAMM-004](https://github.com/vegaprotocol/specs/blob/colosseo/protocol/0090-VAMM-automated_market_maker.md#0014-NP-VAMM-004)

**Comment by Sohill-Patel** [comment] 2024-07-09 08:33
duplicate of https://github.com/vegaprotocol/core-test-coverage/issues/1377

**Closed by Sohill-Patel** 2024-07-09 08:33 UTC
Labels: system-test, hybrid-liquidity
